### ISSUE TITLE
Sprite png

### ISSUE THREAD

**Issue by canislupuslee** [Nikke-db/Nikke-db.github.io#1]
Thank you, but how do you break down the game pack? What tools do you need

I can't find UnityCache when unpacking, please tell me, thank you

by 2022.11.10

**Comment by Nikke-db** [comment]
On android, you can find the unity cache using this path:
root > android > data > com.proximabeta.nikke > files > UnityCache . The assets are in the folder Shared. You can also find  the eb folder ( inside files ) which have encrypted game assets such as l2d and bgm.

This should be accessible even on non rooted devices.

Android emulators should have a similar path.

I have no idea how to access this using other operating softwares such as iOS or Harmony OS.

**Comment by canislupuslee** [comment]
What is the decryption tool? I tried several, but nothing worked

**Comment by Nikke-db** [comment]
https://github.com/FZFalzar/NikkeTools

**Comment by canislupuslee** [comment]
Thank you!
