### ISSUE TITLE
It doesn't work on Spine Web Player

### ISSUE THREAD

**Issue by JiangBoHu** [Nikke-db/Nikke-db.github.io#13]
Help plz, The error message is on my photo.
files: l2d of c470_00
🙏🙏🙏
Official runtime:
http://esotericsoftware.com/spine-player
![Screenshot_2024_0210_123239](https://github.com/Nikke-db/Nikke-db.github.io/assets/52701508/2579c553-d1a7-4225-bd31-13266c486e27)

**Comment by JiangBoHu** [comment]
its l2d of c470_00

**Comment by JiangBoHu** [comment]
files l2d of c470_00

**Comment by Koshirei** [comment]
zip me the files you are using.
I don't know which files of c470 you tried to load , full body, aim or cover? 
the full body is a double-png asset, however the custom spine loader feature can only accept 1 png as of now

**Comment by JiangBoHu** [comment]
> zip me the files you are using. I don't know which files of c470 you tried to load , full body, aim or cover? the full body is a double-png asset, however the custom spine loader feature can only accept 1 png as of now

full body，like other 1-png l2d for version 4.1.* ，so is c942, Their skel can't load

**Comment by JiangBoHu** [comment]
> > zip me the files you are using. I don't know which files of c470 you tried to load , full body, aim or cover? the full body is a double-png asset, however the custom spine loader feature can only accept 1 png as of now
> 
> full body，like other 1-png l2d for version 4.1.* ，so is c942, Their skel can't load

oh, I tried spine-player4.1.js, they are working.
but lower version l2d are breakdown，
Do I have to use both versions of the js file at the same time?

**Comment by Koshirei** [comment]
change the version in the cdn link directy 
js latest 4.0 https://unpkg.com/@esotericsoftware/spine-player@4.0.*/dist/iife/spine-player.min.js .
I don't think there is a 4.0.* css file, but the 4.1.* css should work with the 4.0.* js.  
If you are making you own web spine viewer you'll have to load both files in the front end and use the version you need per asset.
Check out the front repository how I have done it

**Comment by JiangBoHu** [comment]
> change the version in the cdn link directy js latest 4.0 https://unpkg.com/@esotericsoftware/spine-player@4.0.*/dist/iife/spine-player.min.js . I don't think there is a 4.0.* css file, but the 4.1.* css should work with the 4.0.* js. If you are making you own web spine viewer you'll have to load both files in the front end and use the version you need per asset. Check out the front repository how I have done it

Yes, I find the way in you repository 【spine-web-player-template】,
and its also cant run the 2-png l2d right?

**Comment by Koshirei** [comment]
spine web player template should be able to load a two png spine animation.

**Comment by JiangBoHu** [comment]
> spine web player template should be able to load a two png spine animation.

I failed, and it seems that Web Player doesn't support it

**Comment by Koshirei** [comment]
c470_00 is running fine on spine-web-player-template 
![image](https://github.com/Nikke-db/Nikke-db.github.io/assets/76258309/d683a552-7524-427e-b615-402dabac51aa)
I honestly do not understand your issue, where you are trying to load your file, nor which files are you even loading. The error message of the initial post should not appear on nikke-db as I have a custom message written.
if you are making a personal project using spine web player, publish it to git and if I find time I will take a look at it and try to resolve your issues

**Comment by JiangBoHu** [comment]
> c470_00 is running fine on spine-web-player-template ![image](https://private-user-images.githubusercontent.com/76258309/303935813-d683a552-7524-427e-b615-402dabac51aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDI3NDcsIm5iZiI6MTcwNzcwMjQ0NywicGF0aCI6Ii83NjI1ODMwOS8zMDM5MzU4MTMtZDY4M2E1NTItNzUyNC00MjdlLWI2MTUtNDAyZGFiYWM1MWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAxNDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjk3Y2M3N2MxNjJlNThkNWQwMDU4M2ExMzQ3NWJmZTQwZTZiZGE3NzYyYWQ5MWQ4N2E2OGViNzI1NGRjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tj_2IShlUluCx5PtC8THaUeNgAu7ou08lJoGHsnRn9k) I honestly do not understand your issue, where you are trying to load your file, nor which files are you even loading. The error message of the initial post should not appear on nikke-db as I have a custom message written. if you are making a personal project using spine web player, publish it to git and if I find time I will take a look at it and try to resolve your issues

Oh, thats, i want to die, I use the original demo, it works.
Now i remember it, I modified the skel's code by VSCode before I used the spine-player4.1. Even though I pressed Ctrl+z, it was not restored...
![image](https://github.com/Nikke-db/Nikke-db.github.io/assets/52701508/3e5ed7a5-16b7-4d01-9216-617b0731b152)

**Comment by JiangBoHu** [comment]
> c470_00 is running fine on spine-web-player-template ![image](https://private-user-images.githubusercontent.com/76258309/303935813-d683a552-7524-427e-b615-402dabac51aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDM5ODIsIm5iZiI6MTcwNzcwMzY4MiwicGF0aCI6Ii83NjI1ODMwOS8zMDM5MzU4MTMtZDY4M2E1NTItNzUyNC00MjdlLWI2MTUtNDAyZGFiYWM1MWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAyMDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZWQyM2NjMWQ3MzkzOGMyZDRkYzg4ZmE4NTMxNDBjMDc2ZDY5OGJiODhmODkzODM1OWVkODFhMWI3ZDVkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ArzmCz1SFE2nIDQtDqwC9lBDmq7Ek5lFSKlBGR4uW6g) I honestly do not understand your issue, where you are trying to load your file, nor which files are you even loading. The error message of the initial post should not appear on nikke-db as I have a custom message written. if you are making a personal project using spine web player, publish it to git and if I find time I will take a look at it and try to resolve your issues

Oh, thats, i want to die, I use the original demo, it works.
Now i remember it, I modified the skel's code by VSCode before I used the spine-player4.1. Even though I pressed Ctrl+z, it was not restored...

**Comment by JiangBoHu** [comment]
> spine web player template should be able to load a two png spine animation.

I thank you very much, You let me konw that it can be used on original code. Now, It's all right, thank you.
