### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by Elevna1** [Nikke-db/Nikke-db.github.io#17]
I don't know if this is the right place to post this but I can't find any other info on this at all anywhere.
The site hasn't worked for like a month for me. Specifically "https://nikke-db.pages.dev/" which returns a "secure connection failed".
The site "https://nikke-db.github.io" seems to work, yet only for a few seconds, after which it redirects to the .pages one and errors.
Is this an issue only I am having, or is the site been down/broken or something?

**Comment by Koshirei** [comment]
the website is still running
the github.io link have been deprecated for over a year so I make it redirect to the correct website.
first time I'm ever hearing of your issue.

what browser do you use ?
what version of the browser ?
hve you tried another browser ? it's working fine for me on firefox, edge, chrome and GX

what country do you leave in ?
have you tried in incognito ?
have you triee with a proxy or vpn ?

does it happen on other computers of your household ?
does it happen on your phone ?

**Comment by Elevna1** [comment]
Really? I've had this problem with the pages.dev site for a while now.

I switched to firefox recently and it happens on both that and chrome. Newest versions of each.
UK/Yes/No

I just tried it on my phone and it works on there. Odd. 

I have avast, maybe that's somehow blocking it since the error says "Secure Connection Failed"?

**Comment by Koshirei** [comment]
can't know for yourself if avast is the cause of it. I might do researchs this week end but since I cannot reproduce it for myself idk if I'll find anything remotely useful

**Comment by Elevna1** [comment]
I can confirm it's avast. For some reason the website is on Avast's blacklist.
![Screenshot 2024-09-26 195421](https://github.com/user-attachments/assets/6ef5cf31-2c61-42b9-9526-c4cf5c55a471)
How to fix; On avast, click menu -> settings -> exceptions -> add exception
