### ISSUE TITLE
Add Chinese version comics

### ISSUE THREAD

**Issue by pzwboy** [Nikke-db/Nikke-db.github.io#18]
Can you add the Chinese version of NIKKE Comics?

**Comment by Koshirei** [comment]
Send me a link/tutorial on how to **easily** grab the official chinese, for instance a URL filter that'll make it easier to find them one by one.
If the comics are available on Twitter it should be easy to find, but I've never seen an official chinese nikke account.

**Comment by pzwboy** [comment]
NIKKE in China only has a Facebook account
https://www.facebook.com/TW.NIKKE/

**Comment by pzwboy** [comment]
This is one of the Chinese comics: https://www.facebook.com/photo.php?fbid=407434748734453

**Comment by pzwboy** [comment]
![image](https://github.com/user-attachments/assets/1f730178-79bd-4330-a9ab-d394672c4ac9)

**Comment by Koshirei** [comment]
using this link I am able to retrieve 34 chinese comics, but I have no idea how to find the 24 other comics.
Do you know a way to retrieve **all** of the comics ? 
I do not want to do a feature half baked, if I commit to it and maintain it I want to have all 58 pannels.
I will not spend days on end scrolling the facebook page trying to find the missing images as this is way too tedious

https://www.facebook.com/search/photos/?q=【妮姬四格漫畫】

**Comment by pzwboy** [comment]
I found a NIKKE lover in BiliBili. He copied the first 56 comics to his dynamic.

https://space.bilibili.com/8997555/search/dynamic?keyword=%E6%BC%AB%E7%94%BB

**Comment by pzwboy** [comment]
On BiliBili, the image link may look like this: https://i0.hdslb.com/bfs/article/25a19d04f20ec6077bdf58718be4f34d8997555.jpg@1256w_1778h_!web-article-pic.avif

To download the original image, simply delete the "@1256w_1778h_!web-article-pic.avif" at the end of the link.

**Comment by Koshirei** [comment]
alright then I'll add this, not sure when.
I don't have much interest in nikke db anymore
I've been focusing a second website

**Comment by pzwboy** [comment]
I searched again in his Dynamic and found that he copied all 58 of comics.
![image](https://github.com/user-attachments/assets/8a4e0765-150c-4b94-b4e8-c45af9970c58)
